from os.path import join
include: join("rules","init.smk")

localrules: all
rule all:
    input:
        #fastqc
        expand(join(QCDIR,"fastqc","{replicate}.R1_fastqc.zip"), replicate=REPLICATES),
include: join("rules","qc.smk")