## you probably need to change or comment/uncomment some of these
#
# The working dir... output will be in the results subfolder of the workdir
workdir: "WORKDIR"
#
tools: "PIPELINE_HOME/resources/tools.yaml"
scriptsdir: "WORKDIR/scripts"
resourcesdir: "PIPELINE_HOME/resources"
samplemanifest: "WORKDIR/samples.tsv"

genome: "GENOME"
indexdir: "/data/EVset_RNAseq/Pipelines/ERVPipeline/resources"

accid2taxid: "/data/EVset_RNAseq/Pipelines/ERVPipeline/resources/nr/accid2taxid.pkl"
taxid2lineage: "/data/EVset_RNAseq/Pipelines/ERVPipeline/resources/taxadb/ncbi_lineages.csv.gz"
nrtitles: "/data/EVset_RNAseq/Pipelines/ERVPipeline/resources/nr/nr_titles.pkl"
