## you probably need to change or comment/uncomment some of these
#
# The working dir... output will be in the results subfolder of the workdir
workdir: "WORKDIR"
#
tools: "PIPELINE_HOME/resources/tools.yaml"
scriptsdir: "WORKDIR/scripts"
resourcesdir: "PIPELINE_HOME/resources"
samplemanifest: "WORKDIR/samples.tsv"

genome: "GENOME"